### ISSUE TITLE
How to ease in both directions

### ISSUE THREAD

**Issue by cloudorbush** [tienphaw/react-native-easing-gradient#1]
For example:

![image](https://user-images.githubusercontent.com/57633368/158846362-91edb98e-5726-454e-ab36-fbcde14afe90.jpeg)

Is it possible to apply an easing gradient to the right side as well to the bottom side?

Thanks!

**Comment by 10000multiplier** [comment]
Ah looks like `expo-linear-gradient` comes with `start` and `end` props specifically for this purpose.

https://docs.expo.dev/versions/latest/sdk/linear-gradient
