### ISSUE TITLE
Low Gradient quality on 4k TV

### ISSUE THREAD

**Issue by Dav2015** [tienphaw/react-native-easing-gradient#5]
The LinearGradient using [react-native-easing-gradient](https://github.com/phamfoo/react-native-easing-gradient)
Only tested in Android TV

I saw improvements on the quality of the gradient but not enough.
I tried with different extraColorStopsPerTransition, but the result is similar.

On the Android Emulator the result is perfect, but on the TV the result is bad.

```
`    const { colors: gradientColours, locations } = easeGradient({
        colorStops: {
            0.1: {
                color: colors.secondary,
            },
            0.5: {
                color: colors.primary,
            },
            0.9: {
                color: colors.secondary,
            },
        },
        easing: Easing.linear,
        extraColorStopsPerTransition: 1000,
    });`
```

```
`        <LinearGradient
            style={{
                position: 'absolute',
                width: Dimensions.get('window').width,
                height: Dimensions.get('window').height,
            }}
            colors={gradientColours}
            locations={locations}
            useAngle={true}
            angle={90}
        />`
```

Packages
"react-native-linear-gradient": "^2.8.3",
"react-native-easing-gradient": "^1.1.1",

**Running on Emulator**
![image](https://github.com/phamfoo/react-native-easing-gradient/assets/15325275/c67cb627-fdef-4a68-bd93-44fcd3931aef)

**On TV**
![signal-2024-03-01-144001_003](https://github.com/phamfoo/react-native-easing-gradient/assets/15325275/bfc2716a-7394-421d-b1f0-2787bd806e22)
![signal-2024-03-01-144001_002](https://github.com/phamfoo/react-native-easing-gradient/assets/15325275/8179de93-4637-4909-8be0-cebc88f4e9c9)

**Comment by phamfoo** [comment]
How does it look on the TV without using the library?

**Comment by Dav2015** [comment]
> How does it look on the TV without using the library?

The result now is better, without this library.
Not messing more.
